package de.fraunhofer.iosb.trufflehog.service.packetdataprocessor.profinetdataprocessor;

import de.fraunhofer.iosb.trufflehog.command.trufflecommand.ITruffleCommand;
import de.fraunhofer.iosb.trufflehog.util.INotifier;
import de.fraunhofer.iosb.trufflehog.util.Notifier;

/**
 * This class is a runnable notifier service that fetches packet data from the spp_profinet snort plugin, generates
 * packet data objects and packs them into commands.
 * Any other service can register as a listener and will receive the commands generated by this service.
 * The class generalises the different types of inter-process communication.
 *
 * Possible implementations: {@link UnixSocketReceiver}, {@link MessageQueueReceiver}
 *
 * @author Mr. X
 * @version 0.0
 */
public abstract class TruffleReceiver extends Notifier<ITruffleCommand> implements INotifier<ITruffleCommand>, Runnable {

}
