/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver */

#ifndef _Included_edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver
#define _Included_edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver
 * Method:    openIPC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver_openIPC
  (JNIEnv *, jobject);

/*
 * Class:     edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver
 * Method:    closeIPC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver_closeIPC
  (JNIEnv *, jobject);

/*
 * Class:     edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver
 * Method:    getTruffle
 * Signature: ()Ledu/kit/trufflehog/service/packetdataprocessor/profinetdataprocessor/Truffle;
 */
JNIEXPORT jobject JNICALL Java_edu_kit_trufflehog_service_packetdataprocessor_profinetdataprocessor_UnixSocketReceiver_getTruffle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
