#ifndef TRUFFLEHOG_SNORTCOMM_H
#define TRUFFLEHOG_SNORTCOMM_H

const int TRUFFLEHOG_CONNECT_REQUEST = 0x0;
const int TRUFFLEHOG_DISCONNECT_REQUEST = 0x1;
const int SNORT_CONNECT_RESPONSE = 0x2;
const int SNORT_DISCONNECT_RESPONSE = 0x3;

#endif
